export const ADD_TO_REPOLIST = "ADD_TO_REPOLIST"
export const REMOVE_FROM_REPOLIST = "REMOVE_FROM_REPOLIST"
export const UPDATE_REPO_RELEASE = "UPDATE_REPO_RELEASE"
export const UPDATE_REPO_SEEN = "UPDATE_REPO_SEEN"